// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: ethos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EthosBridge_Embed_FullMethodName         = "/ethos.bridge.EthosBridge/Embed"
	EthosBridge_EmbedBatch_FullMethodName    = "/ethos.bridge.EthosBridge/EmbedBatch"
	EthosBridge_Rerank_FullMethodName        = "/ethos.bridge.EthosBridge/Rerank"
	EthosBridge_StoreVector_FullMethodName   = "/ethos.bridge.EthosBridge/StoreVector"
	EthosBridge_SearchVectors_FullMethodName = "/ethos.bridge.EthosBridge/SearchVectors"
	EthosBridge_DeleteVector_FullMethodName  = "/ethos.bridge.EthosBridge/DeleteVector"
	EthosBridge_Compact_FullMethodName       = "/ethos.bridge.EthosBridge/Compact"
	EthosBridge_Ping_FullMethodName          = "/ethos.bridge.EthosBridge/Ping"
)

// EthosBridgeClient is the client API for EthosBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EthosBridgeClient interface {
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	EmbedBatch(ctx context.Context, in *EmbedBatchRequest, opts ...grpc.CallOption) (*EmbedBatchResponse, error)
	Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error)
	StoreVector(ctx context.Context, in *StoreVectorRequest, opts ...grpc.CallOption) (*StoreVectorResponse, error)
	SearchVectors(ctx context.Context, in *SearchVectorsRequest, opts ...grpc.CallOption) (*SearchVectorsResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
	Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type ethosBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewEthosBridgeClient(cc grpc.ClientConnInterface) EthosBridgeClient {
	return &ethosBridgeClient{cc}
}

func (c *ethosBridgeClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, EthosBridge_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) EmbedBatch(ctx context.Context, in *EmbedBatchRequest, opts ...grpc.CallOption) (*EmbedBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedBatchResponse)
	err := c.cc.Invoke(ctx, EthosBridge_EmbedBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RerankResponse)
	err := c.cc.Invoke(ctx, EthosBridge_Rerank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) StoreVector(ctx context.Context, in *StoreVectorRequest, opts ...grpc.CallOption) (*StoreVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreVectorResponse)
	err := c.cc.Invoke(ctx, EthosBridge_StoreVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) SearchVectors(ctx context.Context, in *SearchVectorsRequest, opts ...grpc.CallOption) (*SearchVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVectorsResponse)
	err := c.cc.Invoke(ctx, EthosBridge_SearchVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, EthosBridge_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResponse)
	err := c.cc.Invoke(ctx, EthosBridge_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethosBridgeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, EthosBridge_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EthosBridgeServer is the server API for EthosBridge service.
// All implementations must embed UnimplementedEthosBridgeServer
// for forward compatibility.
type EthosBridgeServer interface {
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	EmbedBatch(context.Context, *EmbedBatchRequest) (*EmbedBatchResponse, error)
	Rerank(context.Context, *RerankRequest) (*RerankResponse, error)
	StoreVector(context.Context, *StoreVectorRequest) (*StoreVectorResponse, error)
	SearchVectors(context.Context, *SearchVectorsRequest) (*SearchVectorsResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	Compact(context.Context, *CompactRequest) (*CompactResponse, error)
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedEthosBridgeServer()
}

// UnimplementedEthosBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEthosBridgeServer struct{}

func (UnimplementedEthosBridgeServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedEthosBridgeServer) EmbedBatch(context.Context, *EmbedBatchRequest) (*EmbedBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedBatch not implemented")
}
func (UnimplementedEthosBridgeServer) Rerank(context.Context, *RerankRequest) (*RerankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedEthosBridgeServer) StoreVector(context.Context, *StoreVectorRequest) (*StoreVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreVector not implemented")
}
func (UnimplementedEthosBridgeServer) SearchVectors(context.Context, *SearchVectorsRequest) (*SearchVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVectors not implemented")
}
func (UnimplementedEthosBridgeServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedEthosBridgeServer) Compact(context.Context, *CompactRequest) (*CompactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedEthosBridgeServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEthosBridgeServer) mustEmbedUnimplementedEthosBridgeServer() {}
func (UnimplementedEthosBridgeServer) testEmbeddedByValue()                     {}

// UnsafeEthosBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EthosBridgeServer will
// result in compilation errors.
type UnsafeEthosBridgeServer interface {
	mustEmbedUnimplementedEthosBridgeServer()
}

func RegisterEthosBridgeServer(s grpc.ServiceRegistrar, srv EthosBridgeServer) {
	// If the following call panics, it indicates UnimplementedEthosBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EthosBridge_ServiceDesc, srv)
}

func _EthosBridge_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_EmbedBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).EmbedBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_EmbedBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).EmbedBatch(ctx, req.(*EmbedBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).Rerank(ctx, req.(*RerankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_StoreVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).StoreVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_StoreVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).StoreVector(ctx, req.(*StoreVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_SearchVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).SearchVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_SearchVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).SearchVectors(ctx, req.(*SearchVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).Compact(ctx, req.(*CompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthosBridge_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthosBridgeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthosBridge_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthosBridgeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EthosBridge_ServiceDesc is the grpc.ServiceDesc for EthosBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EthosBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ethos.bridge.EthosBridge",
	HandlerType: (*EthosBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _EthosBridge_Embed_Handler,
		},
		{
			MethodName: "EmbedBatch",
			Handler:    _EthosBridge_EmbedBatch_Handler,
		},
		{
			MethodName: "Rerank",
			Handler:    _EthosBridge_Rerank_Handler,
		},
		{
			MethodName: "StoreVector",
			Handler:    _EthosBridge_StoreVector_Handler,
		},
		{
			MethodName: "SearchVectors",
			Handler:    _EthosBridge_SearchVectors_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _EthosBridge_DeleteVector_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _EthosBridge_Compact_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _EthosBridge_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ethos.proto",
}
