# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ethos_pb2 as ethos__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ethos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EthosBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/ethos.bridge.EthosBridge/Embed',
                request_serializer=ethos__pb2.EmbedRequest.SerializeToString,
                response_deserializer=ethos__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/ethos.bridge.EthosBridge/EmbedBatch',
                request_serializer=ethos__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=ethos__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)
        self.Rerank = channel.unary_unary(
                '/ethos.bridge.EthosBridge/Rerank',
                request_serializer=ethos__pb2.RerankRequest.SerializeToString,
                response_deserializer=ethos__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.StoreVector = channel.unary_unary(
                '/ethos.bridge.EthosBridge/StoreVector',
                request_serializer=ethos__pb2.StoreVectorRequest.SerializeToString,
                response_deserializer=ethos__pb2.StoreVectorResponse.FromString,
                _registered_method=True)
        self.SearchVectors = channel.unary_unary(
                '/ethos.bridge.EthosBridge/SearchVectors',
                request_serializer=ethos__pb2.SearchVectorsRequest.SerializeToString,
                response_deserializer=ethos__pb2.SearchVectorsResponse.FromString,
                _registered_method=True)
        self.DeleteVector = channel.unary_unary(
                '/ethos.bridge.EthosBridge/DeleteVector',
                request_serializer=ethos__pb2.DeleteVectorRequest.SerializeToString,
                response_deserializer=ethos__pb2.DeleteVectorResponse.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/ethos.bridge.EthosBridge/Compact',
                request_serializer=ethos__pb2.CompactRequest.SerializeToString,
                response_deserializer=ethos__pb2.CompactResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/ethos.bridge.EthosBridge/Ping',
                request_serializer=ethos__pb2.PingRequest.SerializeToString,
                response_deserializer=ethos__pb2.PongResponse.FromString,
                _registered_method=True)


class EthosBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EthosBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=ethos__pb2.EmbedRequest.FromString,
                    response_serializer=ethos__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=ethos__pb2.EmbedBatchRequest.FromString,
                    response_serializer=ethos__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=ethos__pb2.RerankRequest.FromString,
                    response_serializer=ethos__pb2.RerankResponse.SerializeToString,
            ),
            'StoreVector': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreVector,
                    request_deserializer=ethos__pb2.StoreVectorRequest.FromString,
                    response_serializer=ethos__pb2.StoreVectorResponse.SerializeToString,
            ),
            'SearchVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVectors,
                    request_deserializer=ethos__pb2.SearchVectorsRequest.FromString,
                    response_serializer=ethos__pb2.SearchVectorsResponse.SerializeToString,
            ),
            'DeleteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVector,
                    request_deserializer=ethos__pb2.DeleteVectorRequest.FromString,
                    response_serializer=ethos__pb2.DeleteVectorResponse.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=ethos__pb2.CompactRequest.FromString,
                    response_serializer=ethos__pb2.CompactResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ethos__pb2.PingRequest.FromString,
                    response_serializer=ethos__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ethos.bridge.EthosBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ethos.bridge.EthosBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EthosBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/Embed',
            ethos__pb2.EmbedRequest.SerializeToString,
            ethos__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/EmbedBatch',
            ethos__pb2.EmbedBatchRequest.SerializeToString,
            ethos__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/Rerank',
            ethos__pb2.RerankRequest.SerializeToString,
            ethos__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/StoreVector',
            ethos__pb2.StoreVectorRequest.SerializeToString,
            ethos__pb2.StoreVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/SearchVectors',
            ethos__pb2.SearchVectorsRequest.SerializeToString,
            ethos__pb2.SearchVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/DeleteVector',
            ethos__pb2.DeleteVectorRequest.SerializeToString,
            ethos__pb2.DeleteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/Compact',
            ethos__pb2.CompactRequest.SerializeToString,
            ethos__pb2.CompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ethos.bridge.EthosBridge/Ping',
            ethos__pb2.PingRequest.SerializeToString,
            ethos__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
