// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: overkill.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_overkill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbedBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchRequest) Reset() {
	*x = EmbedBatchRequest{}
	mi := &file_overkill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchRequest) ProtoMessage() {}

func (x *EmbedBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchRequest.ProtoReflect.Descriptor instead.
func (*EmbedBatchRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedBatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *EmbedBatchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Tokens        int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_overkill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type EmbedBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EmbedResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchResponse) Reset() {
	*x = EmbedBatchResponse{}
	mi := &file_overkill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchResponse) ProtoMessage() {}

func (x *EmbedBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchResponse.ProtoReflect.Descriptor instead.
func (*EmbedBatchResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedBatchResponse) GetResults() []*EmbedResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmbedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Tokens        int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResult) Reset() {
	*x = EmbedResult{}
	mi := &file_overkill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResult) ProtoMessage() {}

func (x *EmbedResult) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResult.ProtoReflect.Descriptor instead.
func (*EmbedResult) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedResult) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResult) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type RerankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Documents     []string               `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	TopN          int32                  `protobuf:"varint,4,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankRequest) Reset() {
	*x = RerankRequest{}
	mi := &file_overkill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankRequest) ProtoMessage() {}

func (x *RerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankRequest.ProtoReflect.Descriptor instead.
func (*RerankRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{5}
}

func (x *RerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RerankRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RerankRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type RerankResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,2,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	Text           string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RerankResult) Reset() {
	*x = RerankResult{}
	mi := &file_overkill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResult) ProtoMessage() {}

func (x *RerankResult) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResult.ProtoReflect.Descriptor instead.
func (*RerankResult) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{6}
}

func (x *RerankResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RerankResult) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *RerankResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type RerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RerankResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResponse) Reset() {
	*x = RerankResponse{}
	mi := &file_overkill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResponse) ProtoMessage() {}

func (x *RerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResponse.ProtoReflect.Descriptor instead.
func (*RerankResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{7}
}

func (x *RerankResponse) GetResults() []*RerankResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type VectorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorEntry) Reset() {
	*x = VectorEntry{}
	mi := &file_overkill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorEntry) ProtoMessage() {}

func (x *VectorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorEntry.ProtoReflect.Descriptor instead.
func (*VectorEntry) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{8}
}

func (x *VectorEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorEntry) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *VectorEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VectorEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *VectorEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreVectorRequest) Reset() {
	*x = StoreVectorRequest{}
	mi := &file_overkill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreVectorRequest) ProtoMessage() {}

func (x *StoreVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreVectorRequest.ProtoReflect.Descriptor instead.
func (*StoreVectorRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{9}
}

func (x *StoreVectorRequest) GetEntry() *VectorEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StoreVectorRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type StoreVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreVectorResponse) Reset() {
	*x = StoreVectorResponse{}
	mi := &file_overkill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreVectorResponse) ProtoMessage() {}

func (x *StoreVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreVectorResponse.ProtoReflect.Descriptor instead.
func (*StoreVectorResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{10}
}

func (x *StoreVectorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchVectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVectorsRequest) Reset() {
	*x = SearchVectorsRequest{}
	mi := &file_overkill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorsRequest) ProtoMessage() {}

func (x *SearchVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorsRequest.ProtoReflect.Descriptor instead.
func (*SearchVectorsRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{11}
}

func (x *SearchVectorsRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchVectorsRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchVectorsRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SearchVectorsRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *SearchVectorsRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_overkill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVectorsResponse) Reset() {
	*x = SearchVectorsResponse{}
	mi := &file_overkill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorsResponse) ProtoMessage() {}

func (x *SearchVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorsResponse.ProtoReflect.Descriptor instead.
func (*SearchVectorsResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{13}
}

func (x *SearchVectorsResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorRequest) Reset() {
	*x = DeleteVectorRequest{}
	mi := &file_overkill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorRequest) ProtoMessage() {}

func (x *DeleteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteVectorRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type DeleteVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorResponse) Reset() {
	*x = DeleteVectorResponse{}
	mi := &file_overkill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorResponse) ProtoMessage() {}

func (x *DeleteVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorResponse.ProtoReflect.Descriptor instead.
func (*DeleteVectorResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TargetTokens  int32                  `protobuf:"varint,3,opt,name=target_tokens,json=targetTokens,proto3" json:"target_tokens,omitempty"`
	Style         string                 `protobuf:"bytes,4,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_overkill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{16}
}

func (x *CompactRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompactRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompactRequest) GetTargetTokens() int32 {
	if x != nil {
		return x.TargetTokens
	}
	return 0
}

func (x *CompactRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

type CompactResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Summary        string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	OriginalTokens int32                  `protobuf:"varint,2,opt,name=original_tokens,json=originalTokens,proto3" json:"original_tokens,omitempty"`
	SummaryTokens  int32                  `protobuf:"varint,3,opt,name=summary_tokens,json=summaryTokens,proto3" json:"summary_tokens,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_overkill_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{17}
}

func (x *CompactResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CompactResponse) GetOriginalTokens() int32 {
	if x != nil {
		return x.OriginalTokens
	}
	return 0
}

func (x *CompactResponse) GetSummaryTokens() int32 {
	if x != nil {
		return x.SummaryTokens
	}
	return 0
}

func (x *CompactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_overkill_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{18}
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_overkill_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overkill_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_overkill_proto_rawDescGZIP(), []int{19}
}

func (x *PongResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PongResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_overkill_proto protoreflect.FileDescriptor

const file_overkill_proto_rawDesc = "" +
	"\n" +
	"\x0eoverkill.proto\x12\x0foverkill.bridge\"8\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"?\n" +
	"\x11EmbedBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"E\n" +
	"\rEmbedResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\"L\n" +
	"\x12EmbedBatchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.overkill.bridge.EmbedResultR\aresults\"C\n" +
	"\vEmbedResult\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\"n\n" +
	"\rRerankRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tdocuments\x18\x02 \x03(\tR\tdocuments\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x13\n" +
	"\x05top_n\x18\x04 \x01(\x05R\x04topN\"a\n" +
	"\fRerankResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12'\n" +
	"\x0frelevance_score\x18\x02 \x01(\x01R\x0erelevanceScore\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"I\n" +
	"\x0eRerankResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.overkill.bridge.RerankResultR\aresults\"\xda\x01\n" +
	"\vVectorEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.overkill.bridge.VectorEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x12StoreVectorRequest\x122\n" +
	"\x05entry\x18\x01 \x01(\v2\x1c.overkill.bridge.VectorEntryR\x05entry\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\"?\n" +
	"\x13StoreVectorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x83\x02\n" +
	"\x14SearchVectorsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\x12L\n" +
	"\afilters\x18\x05 \x03(\v22.overkill.bridge.SearchVectorsRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.overkill.bridge.SearchResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x15SearchVectorsResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.overkill.bridge.SearchResultR\aresults\"?\n" +
	"\x13DeleteVectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\"0\n" +
	"\x14DeleteVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"{\n" +
	"\x0eCompactRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rtarget_tokens\x18\x03 \x01(\x05R\ftargetTokens\x12\x14\n" +
	"\x05style\x18\x04 \x01(\tR\x05style\"\x95\x01\n" +
	"\x0fCompactResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12'\n" +
	"\x0foriginal_tokens\x18\x02 \x01(\x05R\x0eoriginalTokens\x12%\n" +
	"\x0esummary_tokens\x18\x03 \x01(\x05R\rsummaryTokens\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPongResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xa1\x05\n" +
	"\vOverkillBridge\x12F\n" +
	"\x05Embed\x12\x1d.overkill.bridge.EmbedRequest\x1a\x1e.overkill.bridge.EmbedResponse\x12U\n" +
	"\n" +
	"EmbedBatch\x12\".overkill.bridge.EmbedBatchRequest\x1a#.overkill.bridge.EmbedBatchResponse\x12I\n" +
	"\x06Rerank\x12\x1e.overkill.bridge.RerankRequest\x1a\x1f.overkill.bridge.RerankResponse\x12X\n" +
	"\vStoreVector\x12#.overkill.bridge.StoreVectorRequest\x1a$.overkill.bridge.StoreVectorResponse\x12^\n" +
	"\rSearchVectors\x12%.overkill.bridge.SearchVectorsRequest\x1a&.overkill.bridge.SearchVectorsResponse\x12[\n" +
	"\fDeleteVector\x12$.overkill.bridge.DeleteVectorRequest\x1a%.overkill.bridge.DeleteVectorResponse\x12L\n" +
	"\aCompact\x12\x1f.overkill.bridge.CompactRequest\x1a .overkill.bridge.CompactResponse\x12C\n" +
	"\x04Ping\x12\x1c.overkill.bridge.PingRequest\x1a\x1d.overkill.bridge.PongResponseB1Z/github.com/Sahaj-Tech-ltd/overkill/bridge/protob\x06proto3"

var (
	file_overkill_proto_rawDescOnce sync.Once
	file_overkill_proto_rawDescData []byte
)

func file_overkill_proto_rawDescGZIP() []byte {
	file_overkill_proto_rawDescOnce.Do(func() {
		file_overkill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overkill_proto_rawDesc), len(file_overkill_proto_rawDesc)))
	})
	return file_overkill_proto_rawDescData
}

var file_overkill_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_overkill_proto_goTypes = []any{
	(*EmbedRequest)(nil),          // 0: overkill.bridge.EmbedRequest
	(*EmbedBatchRequest)(nil),     // 1: overkill.bridge.EmbedBatchRequest
	(*EmbedResponse)(nil),         // 2: overkill.bridge.EmbedResponse
	(*EmbedBatchResponse)(nil),    // 3: overkill.bridge.EmbedBatchResponse
	(*EmbedResult)(nil),           // 4: overkill.bridge.EmbedResult
	(*RerankRequest)(nil),         // 5: overkill.bridge.RerankRequest
	(*RerankResult)(nil),          // 6: overkill.bridge.RerankResult
	(*RerankResponse)(nil),        // 7: overkill.bridge.RerankResponse
	(*VectorEntry)(nil),           // 8: overkill.bridge.VectorEntry
	(*StoreVectorRequest)(nil),    // 9: overkill.bridge.StoreVectorRequest
	(*StoreVectorResponse)(nil),   // 10: overkill.bridge.StoreVectorResponse
	(*SearchVectorsRequest)(nil),  // 11: overkill.bridge.SearchVectorsRequest
	(*SearchResult)(nil),          // 12: overkill.bridge.SearchResult
	(*SearchVectorsResponse)(nil), // 13: overkill.bridge.SearchVectorsResponse
	(*DeleteVectorRequest)(nil),   // 14: overkill.bridge.DeleteVectorRequest
	(*DeleteVectorResponse)(nil),  // 15: overkill.bridge.DeleteVectorResponse
	(*CompactRequest)(nil),        // 16: overkill.bridge.CompactRequest
	(*CompactResponse)(nil),       // 17: overkill.bridge.CompactResponse
	(*PingRequest)(nil),           // 18: overkill.bridge.PingRequest
	(*PongResponse)(nil),          // 19: overkill.bridge.PongResponse
	nil,                           // 20: overkill.bridge.VectorEntry.MetadataEntry
	nil,                           // 21: overkill.bridge.SearchVectorsRequest.FiltersEntry
	nil,                           // 22: overkill.bridge.SearchResult.MetadataEntry
}
var file_overkill_proto_depIdxs = []int32{
	4,  // 0: overkill.bridge.EmbedBatchResponse.results:type_name -> overkill.bridge.EmbedResult
	6,  // 1: overkill.bridge.RerankResponse.results:type_name -> overkill.bridge.RerankResult
	20, // 2: overkill.bridge.VectorEntry.metadata:type_name -> overkill.bridge.VectorEntry.MetadataEntry
	8,  // 3: overkill.bridge.StoreVectorRequest.entry:type_name -> overkill.bridge.VectorEntry
	21, // 4: overkill.bridge.SearchVectorsRequest.filters:type_name -> overkill.bridge.SearchVectorsRequest.FiltersEntry
	22, // 5: overkill.bridge.SearchResult.metadata:type_name -> overkill.bridge.SearchResult.MetadataEntry
	12, // 6: overkill.bridge.SearchVectorsResponse.results:type_name -> overkill.bridge.SearchResult
	0,  // 7: overkill.bridge.OverkillBridge.Embed:input_type -> overkill.bridge.EmbedRequest
	1,  // 8: overkill.bridge.OverkillBridge.EmbedBatch:input_type -> overkill.bridge.EmbedBatchRequest
	5,  // 9: overkill.bridge.OverkillBridge.Rerank:input_type -> overkill.bridge.RerankRequest
	9,  // 10: overkill.bridge.OverkillBridge.StoreVector:input_type -> overkill.bridge.StoreVectorRequest
	11, // 11: overkill.bridge.OverkillBridge.SearchVectors:input_type -> overkill.bridge.SearchVectorsRequest
	14, // 12: overkill.bridge.OverkillBridge.DeleteVector:input_type -> overkill.bridge.DeleteVectorRequest
	16, // 13: overkill.bridge.OverkillBridge.Compact:input_type -> overkill.bridge.CompactRequest
	18, // 14: overkill.bridge.OverkillBridge.Ping:input_type -> overkill.bridge.PingRequest
	2,  // 15: overkill.bridge.OverkillBridge.Embed:output_type -> overkill.bridge.EmbedResponse
	3,  // 16: overkill.bridge.OverkillBridge.EmbedBatch:output_type -> overkill.bridge.EmbedBatchResponse
	7,  // 17: overkill.bridge.OverkillBridge.Rerank:output_type -> overkill.bridge.RerankResponse
	10, // 18: overkill.bridge.OverkillBridge.StoreVector:output_type -> overkill.bridge.StoreVectorResponse
	13, // 19: overkill.bridge.OverkillBridge.SearchVectors:output_type -> overkill.bridge.SearchVectorsResponse
	15, // 20: overkill.bridge.OverkillBridge.DeleteVector:output_type -> overkill.bridge.DeleteVectorResponse
	17, // 21: overkill.bridge.OverkillBridge.Compact:output_type -> overkill.bridge.CompactResponse
	19, // 22: overkill.bridge.OverkillBridge.Ping:output_type -> overkill.bridge.PongResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_overkill_proto_init() }
func file_overkill_proto_init() {
	if File_overkill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overkill_proto_rawDesc), len(file_overkill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_overkill_proto_goTypes,
		DependencyIndexes: file_overkill_proto_depIdxs,
		MessageInfos:      file_overkill_proto_msgTypes,
	}.Build()
	File_overkill_proto = out.File
	file_overkill_proto_goTypes = nil
	file_overkill_proto_depIdxs = nil
}
