package session

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestProbe_EmptyDirIsHealthy(t *testing.T) {
	res := Probe("", "")
	if res.Corrupt {
		t.Error("empty dir should not report corrupt")
	}
}

func TestProbe_NonexistentDirIsHealthy(t *testing.T) {
	res := Probe("/this/does/not/exist", "")
	if res.Corrupt {
		t.Error("missing dir is fresh-install, not corruption")
	}
}

func TestProbe_FreshBadgerHealthy(t *testing.T) {
	dir := t.TempDir()
	// Create-and-close a healthy store first so there's something to probe.
	store, err := NewBadgerStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	store.Close()

	res := Probe(dir, "")
	if res.Corrupt {
		t.Errorf("healthy store reported corrupt: %s", res.Cause)
	}
}

func TestProbe_CorruptVLogIsDetected(t *testing.T) {
	dir := t.TempDir()
	// Init a real Badger so there are files to corrupt.
	store, err := NewBadgerStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	store.Close()

	// Find any .vlog file and overwrite the header with garbage so
	// the next Open fails parsing the value log.
	matches, err := filepath.Glob(filepath.Join(dir, "*.vlog"))
	if err != nil || len(matches) == 0 {
		t.Skip("no .vlog files generated by Badger in this environment")
	}
	if err := os.WriteFile(matches[0], []byte("CORRUPTED-NOT-A-VLOG"), 0o644); err != nil {
		t.Fatal(err)
	}

	res := Probe(dir, "")
	if !res.Corrupt {
		t.Errorf("corrupt vlog should be detected, got %+v", res)
	}
	if res.Cause == "" {
		t.Error("Corrupt result should explain why")
	}
}

func TestProbe_ExportFoundIsReported(t *testing.T) {
	dir := t.TempDir()
	exportDir := t.TempDir()
	exportPath := filepath.Join(exportDir, "memory-export.md")
	if err := os.WriteFile(exportPath, []byte("# Export\n\n## Sessions\n\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	res := Probe(dir, exportPath)
	if !res.ExportFound {
		t.Error("expected ExportFound=true when export file exists")
	}
}

func TestProbe_EmptyExportNotReported(t *testing.T) {
	dir := t.TempDir()
	exportPath := filepath.Join(t.TempDir(), "memory-export.md")
	_ = os.WriteFile(exportPath, []byte(""), 0o644)
	res := Probe(dir, exportPath)
	if res.ExportFound {
		t.Error("empty export file should not count")
	}
}

func TestCorruptionNotice_WithExport(t *testing.T) {
	res := ProbeResult{
		Corrupt:     true,
		Cause:       "test cause",
		ExportFound: true,
		ExportPath:  "/path/to/export.md",
	}
	notice := res.CorruptionNotice()
	for _, want := range []string{"corrupted", "test cause", "/path/to/export.md", "restore"} {
		if !strings.Contains(strings.ToLower(notice), strings.ToLower(want)) {
			t.Errorf("notice missing %q: %s", want, notice)
		}
	}
}

func TestCorruptionNotice_NoExportSuggestsRestore(t *testing.T) {
	res := ProbeResult{
		Corrupt: true,
		Cause:   "test cause",
	}
	notice := res.CorruptionNotice()
	if !strings.Contains(notice, "starting fresh") {
		t.Errorf("no-export path should say 'starting fresh', got %s", notice)
	}
}

func TestCorruptionNotice_HealthyIsEmpty(t *testing.T) {
	res := ProbeResult{Corrupt: false}
	if got := res.CorruptionNotice(); got != "" {
		t.Errorf("healthy probe should produce empty notice, got %q", got)
	}
}

// ---------------------------------------------------------------------------
// CheckOnBoot
// ---------------------------------------------------------------------------

func TestCheckOnBoot_HealthyDoesNotAlert(t *testing.T) {
	dir := t.TempDir()
	store, err := NewBadgerStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	store.Close()

	called := false
	res := CheckOnBoot(dir, "", func(alertType, message, sessionID string) error {
		called = true
		return nil
	})
	if res.Corrupt {
		t.Error("healthy store should not report corrupt")
	}
	if called {
		t.Error("healthy store should NOT trigger alert callback")
	}
}

func TestCheckOnBoot_CorruptCallsAlert(t *testing.T) {
	dir := t.TempDir()
	// Create a store, close it, then corrupt MANIFEST (Badger always checks it)
	store, err := NewBadgerStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	store.Close()

	// Corrupt the MANIFEST file — Badger refuses to open a broken manifest
	manifest := filepath.Join(dir, "MANIFEST")
	_ = os.WriteFile(manifest, []byte("CORRUPTED-MANIFEST-NOT-VALID"), 0o644)

	var gotType, gotMsg, gotSID string
	res := CheckOnBoot(dir, "", func(alertType, message, sessionID string) error {
		gotType, gotMsg, gotSID = alertType, message, sessionID
		return nil
	})

	if !res.Corrupt {
		t.Fatalf("corrupt manifest should be detected; cause=%q", res.Cause)
	}
	if gotType != "memory_corruption" {
		t.Errorf("alert type = %q, want memory_corruption", gotType)
	}
	if gotMsg == "" {
		t.Error("alert message should not be empty")
	}
	if gotSID != "" {
		t.Errorf("session ID should be empty for system alert, got %q", gotSID)
	}
}

func TestCheckOnBoot_CorruptWithExport(t *testing.T) {
	dir := t.TempDir()
	exportPath := filepath.Join(t.TempDir(), "memory-export.md")
	_ = os.WriteFile(exportPath, []byte("# Export\n"), 0o644)

	store, err := NewBadgerStore(dir)
	if err != nil {
		t.Fatal(err)
	}
	store.Close()

	_ = os.WriteFile(filepath.Join(dir, "MANIFEST"), []byte("CORRUPTED"), 0o644)

	var gotMsg string
	CheckOnBoot(dir, exportPath, func(_, message, _ string) error {
		gotMsg = message
		return nil
	})

	if !strings.Contains(gotMsg, "restore") {
		t.Errorf("corrupt+export message should mention restore: %q", gotMsg)
	}
}

func TestCheckOnBoot_MissingDirIsHealthy(t *testing.T) {
	called := false
	res := CheckOnBoot("/nonexistent/path/12345", "", func(_, _, _ string) error {
		called = true
		return nil
	})
	if res.Corrupt {
		t.Error("missing dir is fresh install, not corruption")
	}
	if called {
		t.Error("should not alert on missing dir")
	}
}
