// Package share renders a session as a self-contained HTML page and uploads
// it to a paste service for easy URL-based sharing.
package share

import (
	"bytes"
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/Sahaj-Tech-ltd/ethos/internal/session"
)

// Render produces a single-file HTML doc (inlined CSS, no JS) showing the
// conversation. Each message has role, content, tool calls collapsed, and
// timestamps. Style is a clean dark theme matching the TUI palette.
func Render(s *session.Session) (string, error) {
	if s == nil {
		return "", fmt.Errorf("share: nil session")
	}
	var b bytes.Buffer
	title := s.Title
	if title == "" {
		title = "Ethos Session " + s.ID
	}
	b.WriteString("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">")
	fmt.Fprintf(&b, "<title>%s</title>", html.EscapeString(title))
	b.WriteString(`<meta name="viewport" content="width=device-width,initial-scale=1">`)
	b.WriteString("<style>")
	b.WriteString(css)
	b.WriteString("</style></head><body>")

	fmt.Fprintf(&b, `<header><h1>%s</h1>`, html.EscapeString(title))
	fmt.Fprintf(&b, `<div class="meta">`)
	fmt.Fprintf(&b, `<span>session %s</span>`, html.EscapeString(s.ID))
	if s.Model != "" {
		fmt.Fprintf(&b, ` &middot; <span>model %s</span>`, html.EscapeString(s.Model))
	}
	if s.Provider != "" {
		fmt.Fprintf(&b, ` &middot; <span>via %s</span>`, html.EscapeString(s.Provider))
	}
	fmt.Fprintf(&b, ` &middot; <span>%s</span>`, s.UpdatedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, `</div></header>`)

	b.WriteString(`<main>`)
	for i, m := range s.Messages {
		role := strings.ToLower(m.Role)
		if role == "" {
			role = "system"
		}
		fmt.Fprintf(&b, `<article class="msg msg-%s">`, html.EscapeString(role))
		fmt.Fprintf(&b, `<div class="role">%s</div>`, html.EscapeString(strings.ToUpper(role)))
		// Render content as escaped pre — keeps formatting without needing a
		// markdown library at the cost of fancy rendering.
		if strings.TrimSpace(m.Content) != "" {
			fmt.Fprintf(&b, `<pre class="content">%s</pre>`, html.EscapeString(m.Content))
		}
		for _, tc := range m.ToolCalls {
			fmt.Fprintf(&b, `<details class="toolcall"><summary>tool: %s</summary><pre>%s</pre></details>`,
				html.EscapeString(tc.Name), html.EscapeString(tc.Arguments))
		}
		fmt.Fprintf(&b, `</article>`)
		_ = i
	}
	b.WriteString(`</main>`)
	b.WriteString(`<footer>generated by ethos</footer>`)
	b.WriteString("</body></html>")
	return b.String(), nil
}

const css = `
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; background: #0c0d10; color: #d6d8dc; font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; }
header { padding: 32px 24px 18px; border-bottom: 1px solid #1f2128; }
header h1 { margin: 0 0 6px; font-size: 22px; font-weight: 600; letter-spacing: -0.01em; }
.meta { font-size: 12px; color: #6e7180; }
main { max-width: 880px; margin: 0 auto; padding: 24px; display: grid; gap: 18px; }
.msg { padding: 14px 16px; border-radius: 8px; background: #14161c; border: 1px solid #20232c; }
.msg-user { background: #15202b; border-color: #2d4254; }
.msg-assistant { background: #14161c; }
.msg-tool, .msg-system { background: #11131a; color: #9aa0aa; font-size: 13px; }
.role { font-size: 11px; letter-spacing: 0.08em; color: #6e7180; margin-bottom: 8px; text-transform: uppercase; }
.content { margin: 0; white-space: pre-wrap; word-wrap: break-word; font: inherit; color: inherit; background: transparent; }
.toolcall { margin-top: 8px; font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 12px; }
.toolcall summary { cursor: pointer; color: #7b8190; }
.toolcall pre { background: #0a0b0e; padding: 8px; border-radius: 6px; overflow-x: auto; margin-top: 6px; }
footer { text-align: center; color: #4d5060; font-size: 11px; padding: 24px 0 32px; }
`
