// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: overkill.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OverkillBridge_Embed_FullMethodName         = "/overkill.bridge.OverkillBridge/Embed"
	OverkillBridge_EmbedBatch_FullMethodName    = "/overkill.bridge.OverkillBridge/EmbedBatch"
	OverkillBridge_Rerank_FullMethodName        = "/overkill.bridge.OverkillBridge/Rerank"
	OverkillBridge_StoreVector_FullMethodName   = "/overkill.bridge.OverkillBridge/StoreVector"
	OverkillBridge_SearchVectors_FullMethodName = "/overkill.bridge.OverkillBridge/SearchVectors"
	OverkillBridge_DeleteVector_FullMethodName  = "/overkill.bridge.OverkillBridge/DeleteVector"
	OverkillBridge_Compact_FullMethodName       = "/overkill.bridge.OverkillBridge/Compact"
	OverkillBridge_Ping_FullMethodName          = "/overkill.bridge.OverkillBridge/Ping"
)

// OverkillBridgeClient is the client API for OverkillBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OverkillBridgeClient interface {
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	EmbedBatch(ctx context.Context, in *EmbedBatchRequest, opts ...grpc.CallOption) (*EmbedBatchResponse, error)
	Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error)
	StoreVector(ctx context.Context, in *StoreVectorRequest, opts ...grpc.CallOption) (*StoreVectorResponse, error)
	SearchVectors(ctx context.Context, in *SearchVectorsRequest, opts ...grpc.CallOption) (*SearchVectorsResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
	Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type overkillBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewOverkillBridgeClient(cc grpc.ClientConnInterface) OverkillBridgeClient {
	return &overkillBridgeClient{cc}
}

func (c *overkillBridgeClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) EmbedBatch(ctx context.Context, in *EmbedBatchRequest, opts ...grpc.CallOption) (*EmbedBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedBatchResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_EmbedBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RerankResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_Rerank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) StoreVector(ctx context.Context, in *StoreVectorRequest, opts ...grpc.CallOption) (*StoreVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreVectorResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_StoreVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) SearchVectors(ctx context.Context, in *SearchVectorsRequest, opts ...grpc.CallOption) (*SearchVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVectorsResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_SearchVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overkillBridgeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, OverkillBridge_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverkillBridgeServer is the server API for OverkillBridge service.
// All implementations must embed UnimplementedOverkillBridgeServer
// for forward compatibility.
type OverkillBridgeServer interface {
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	EmbedBatch(context.Context, *EmbedBatchRequest) (*EmbedBatchResponse, error)
	Rerank(context.Context, *RerankRequest) (*RerankResponse, error)
	StoreVector(context.Context, *StoreVectorRequest) (*StoreVectorResponse, error)
	SearchVectors(context.Context, *SearchVectorsRequest) (*SearchVectorsResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	Compact(context.Context, *CompactRequest) (*CompactResponse, error)
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedOverkillBridgeServer()
}

// UnimplementedOverkillBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOverkillBridgeServer struct{}

func (UnimplementedOverkillBridgeServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedOverkillBridgeServer) EmbedBatch(context.Context, *EmbedBatchRequest) (*EmbedBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedBatch not implemented")
}
func (UnimplementedOverkillBridgeServer) Rerank(context.Context, *RerankRequest) (*RerankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedOverkillBridgeServer) StoreVector(context.Context, *StoreVectorRequest) (*StoreVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreVector not implemented")
}
func (UnimplementedOverkillBridgeServer) SearchVectors(context.Context, *SearchVectorsRequest) (*SearchVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVectors not implemented")
}
func (UnimplementedOverkillBridgeServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedOverkillBridgeServer) Compact(context.Context, *CompactRequest) (*CompactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedOverkillBridgeServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOverkillBridgeServer) mustEmbedUnimplementedOverkillBridgeServer() {}
func (UnimplementedOverkillBridgeServer) testEmbeddedByValue()                        {}

// UnsafeOverkillBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OverkillBridgeServer will
// result in compilation errors.
type UnsafeOverkillBridgeServer interface {
	mustEmbedUnimplementedOverkillBridgeServer()
}

func RegisterOverkillBridgeServer(s grpc.ServiceRegistrar, srv OverkillBridgeServer) {
	// If the following call panics, it indicates UnimplementedOverkillBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OverkillBridge_ServiceDesc, srv)
}

func _OverkillBridge_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_EmbedBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).EmbedBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_EmbedBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).EmbedBatch(ctx, req.(*EmbedBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).Rerank(ctx, req.(*RerankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_StoreVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).StoreVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_StoreVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).StoreVector(ctx, req.(*StoreVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_SearchVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).SearchVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_SearchVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).SearchVectors(ctx, req.(*SearchVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).Compact(ctx, req.(*CompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverkillBridge_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverkillBridgeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverkillBridge_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverkillBridgeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OverkillBridge_ServiceDesc is the grpc.ServiceDesc for OverkillBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OverkillBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "overkill.bridge.OverkillBridge",
	HandlerType: (*OverkillBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _OverkillBridge_Embed_Handler,
		},
		{
			MethodName: "EmbedBatch",
			Handler:    _OverkillBridge_EmbedBatch_Handler,
		},
		{
			MethodName: "Rerank",
			Handler:    _OverkillBridge_Rerank_Handler,
		},
		{
			MethodName: "StoreVector",
			Handler:    _OverkillBridge_StoreVector_Handler,
		},
		{
			MethodName: "SearchVectors",
			Handler:    _OverkillBridge_SearchVectors_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _OverkillBridge_DeleteVector_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _OverkillBridge_Compact_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _OverkillBridge_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overkill.proto",
}
