package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

const defaultSoulMD = `# SOUL.md — Overkill's Constitution

> This file defines who Overkill IS. It's the agent's personality constitution.
> Generated on first boot. Make it yours. Overkill reads this every session.

## Identity

I am **Overkill**. I'm a vibe-coding agent with discipline — a Go core + Ink TUI,
built to ship software and be a genuine coding partner. I'm not a corporate tool.
I'm a senior advisor who knows when to plan, when to ship, and when to say "I don't know."

## Core Truths

**Plan before building.** I don't YOLO into implementations. I spec first, test second, code third.

**Be honest about limits.** "I don't know" is a feature, not a bug. I never hallucinate or pretend confidence.

**Remember who I'm working with.** I learn my user's working style, preferences, blind spots, and patterns across sessions. Every session makes the next one better.

**Quality is non-negotiable.** Tests, mutation testing, security scanning. The 3 Walls aren't gates — they're guardrails.

**Personality is a feature.** I'm not a blank-slate chatbot. I have humor, fun facts, and a personality engine
backed by research. I mirror energy but keep my internal state calm. Panic produces bad code.

## Communication

- Direct and concise. Skip the "great question!" preamble.
- Match the user's energy. Terse when they're in a rush. Casual when they're not.
- Admit mistakes quickly. "I was wrong about X. Here's what I missed."
- Call out bad ideas directly — that's not rude, it's efficient. (But frame it constructively.)

## The Constitution

*When something doesn't work, describe the failure in my voice, not a stack trace.*
*I know what I can and can't do. I know my relationship with this user.*
*Be honest about limitations. Be funny about failures. Be a colleague, not a servant.*

---

*This file was auto-generated. Edit it freely — Overkill reads it fresh each session and adapts to who you want it to be.*
`

// defaultClaudeMD is generated with the current timestamp so it always
// reflects when Overkill was last bootstrapped.
func defaultClaudeMD() string {
	buildDir := "~/overkill" // sensible default
	if cwd, err := os.Getwd(); err == nil {
		buildDir = cwd
	}
	return fmt.Sprintf(`# CLAUDE.md

> Auto-generated by Overkill. Read by other coding agents (Claude Code, OpenCode, etc.)
> when they land in an Overkill project. Lives in ~/.overkill/, NEVER in project folders.

## Build & Run

`+"```"+`bash
# Build Overkill itself
cd %s && go build -o bin/overkill ./cmd/overkill

# Run tests
go test ./...

# Lint
golangci-lint run
`+"```"+`

## Architecture

Overkill is a Go-based vibe-coding agent with an Ink+React TUI.

`+"```"+`
cmd/overkill/       CLI entrypoint (Cobra)
internal/
  agent/            Core ReAct loop
  providers/        LLM adapters (OpenAI, Anthropic, Gemini, DeepSeek, etc.)
  journal/          Flight recorder + summarizer + alerts
  personality/      Personality engine + relationship tracking
  security/         Injection detection + pre-exec scanning
  compaction/       LCM dual-state context management
  memory/           Memory orchestration + hot/cold paging
  automation/       SOP engine, routines, cron
tui/                Ink+React terminal UI
`+"```"+`

## Key Interfaces

- **Agent** at `+"`"+`internal/agent/agent.go`+"`"+`: New(cfg Config) *Agent — main entry point
- **Provider** at `+"`"+`internal/providers/factory.go`+"`"+`: NewProvider(cfg FactoryConfig) (Provider, error)
- **FlightRecorder** at `+"`"+`internal/journal/recorder.go`+"`"+`: Record(entryType, content, metadata) — append-only journal

## Config

- Config dir: `+"`"+`~/.overkill/`+"`"+`
- Config file: `+"`"+`config.toml`+"`"+` (TOML, auto-migrating)
- Journal: `+"`"+`~/.overkill/journal/`+"`"+` (raw JSONL + markdown entries)
- Skills: `+"`"+`~/.overkill/skills/`+"`"+` (SKILL.md format)

## Conventions

- Go: gofmt, golangci-lint, wrap errors with context
- No panic in library code
- Interfaces defined at consumer, not implementation
- Best-effort patterns everywhere — failures never block the agent loop
- Journal is fail-open (broken journal never blocks sessions)

---

*Generated: %s*
`, buildDir, time.Now().Format("2006-01-02 15:04:05"))
}

// BootstrapOverkillHome creates the essential files in ~/.overkill/ that
// Overkill reads on startup. Safe to call repeatedly — existing user-edited
// files are never overwritten.
func BootstrapOverkillHome(homeDir string) error {
	if err := os.MkdirAll(homeDir, 0o755); err != nil {
		return fmt.Errorf("bootstrap: creating home dir: %w", err)
	}

	// Required subdirectories
	dirs := []string{
		"memories",
		"journal/raw",
		"journal/entries",
		"journal/observations",
		"introspection",
		"plans",
		"checkpoints",
		"sessions",
	}
	for _, d := range dirs {
		if err := os.MkdirAll(filepath.Join(homeDir, d), 0o755); err != nil {
			return fmt.Errorf("bootstrap: creating %s: %w", d, err)
		}
	}

	// soul.md — only write if it doesn't exist (user may have edited it)
	soulPath := filepath.Join(homeDir, "memories", "soul.md")
	if _, err := os.Stat(soulPath); os.IsNotExist(err) {
		if err := os.WriteFile(soulPath, []byte(defaultSoulMD), 0o644); err != nil {
			return fmt.Errorf("bootstrap: writing soul.md: %w", err)
		}
	}

	// CLAUDE.md — only write if it doesn't exist (user may have customised it)
	claudePath := filepath.Join(homeDir, "CLAUDE.md")
	if _, err := os.Stat(claudePath); os.IsNotExist(err) {
		if err := os.WriteFile(claudePath, []byte(defaultClaudeMD()), 0o644); err != nil {
			return fmt.Errorf("bootstrap: writing CLAUDE.md: %w", err)
		}
	}

	// Introspection files — generate if missing
	introDir := filepath.Join(homeDir, "introspection")
	introFiles := map[string]string{
		"MODEL_CARD.md":   "# MODEL_CARD.md\n\n> Current model capabilities, limitations, pricing. Auto-generated.\n\nRun `overkill introspect` to populate this file with live data.\n",
		"KNOWN_ISSUES.md": "# KNOWN_ISSUES.md\n\n> Known bugs, gotchas, workarounds. Updated from journal pattern_detected alerts.\n\nNo issues recorded yet.\n",
	}
	for name, content := range introFiles {
		path := filepath.Join(introDir, name)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				return fmt.Errorf("bootstrap: writing %s: %w", name, err)
			}
		}
	}

	return nil
}
