services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: databunker-vps
    volumes:
      - ./config:/var/syncthing/config
      - ./data:/var/syncthing/data
    ports:
      - "127.0.0.1:8384:8384"   # Web UI (proxied by Caddy)
      - "22000:22000/tcp"        # Sync protocol TCP
      - "22000:22000/udp"        # Sync protocol QUIC
      - "21027:21027/udp"        # Local discovery
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
